export const TOKENS = {
    SessionRepository: Symbol.for("SessionRepository"),
    OrderRepository: Symbol.for("OrderRepository"),
    MenuItemRepository: Symbol.for("MenuItemRepository"),
    EventBus: Symbol.for("EventBus"),
    CreateSessionUseCase: Symbol.for("CreateSessionUseCase"),
    CloseSessionUseCase: Symbol.for("CloseSessionUseCase"),
    GetSessionByCodeUseCase: Symbol.for("GetSessionByCodeUseCase"),
    CreateOrderUseCase: Symbol.for("CreateOrderUseCase"),
    UpdateOrderStatusUseCase: Symbol.for("UpdateOrderStatusUseCase"),
    CancelOrderUseCase: Symbol.for("CancelOrderUseCase"),
    GetSessionOrdersUseCase: Symbol.for("GetSessionOrdersUseCase"),
    GetMenuUseCase: Symbol.for("GetMenuUseCase"),
    CreateMenuItemUseCase: Symbol.for("CreateMenuItemUseCase"),
    UpdateMenuItemUseCase: Symbol.for("UpdateMenuItemUseCase"),
    DeleteMenuItemUseCase: Symbol.for("DeleteMenuItemUseCase"),
} as const;
