name: Publish React Clean

on:
    push:
        branches: [main]
        paths:
            - "packages/react-clean/**"

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4

            # Esperar a que el CI termine correctamente
            - name: Wait for CI to complete
              uses: fountainhead/action-wait-for-check@v1.2.0
              id: wait-for-ci
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  checkName: main
                  ref: ${{ github.sha }}
                  timeoutSeconds: 600
                  intervalSeconds: 10

            # Solo publicar si CI pasó
            - name: Publish package
              if: steps.wait-for-ci.outputs.conclusion == 'success'
              working-directory: packages/react-clean
              run: npx jsr publish
